### ISSUE TITLE
MAX Cube loses all configuration

### ISSUE THREAD

**Issue by claudioita** [Bouni/max-cube-protocol#39]
I use your component through Home Assistant (the Homegear component is based on your code).
As you can see from this discussion, with it the MAX Cube gets reset and loses all configuration
https://community.openhab.org/t/max-cube-looses-all-settings-with-openhab/8537/50

It seems that a solution is to reduce polling to 5 minutes and not less.

IS it possible to have this with your code?

Thanks

**Comment by Bouni** [comment]
What do you mean with code?
This repo is just the documentation of the reverse engineered protocol.
If you want to have an addition in the documentation, feel free to submit a pull request!

**Comment by claudioita** [comment]
I don't know how to request this feature

**Comment by asantaga** [comment]
Claudio, you need to post this query to the home assistant github issue list

https://github.com/home-assistant/home-assistant/issues

Additionally looking at the code it would appear trivial to add the 5min delay (instead of 60s), by editing line 72. I suggest you try it out, if it works then clone, create a branch, then create a PR for the orginal authors

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/maxcube.py

**Comment by claudioita** [comment]
I see, I will try the change myself. I do have hassio, I guess I need to crerate a custom_component. Can you tell me how?

**Comment by asantaga** [comment]
im not at home but im guessing if you search for the file maxcube.py you should be able to simply edit the file

**Comment by claudioita** [comment]
I did change the file and then did this, but received the error as in the
post

https://community.home-assistant.io/t/creating-custom-component-for-the-eq-3-max-cube-how-to/43974/2?u=claudio
